# Generated by Django 3.1.3 on 2021-04-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_bgp', '0005_netbox_bgp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpsession',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
