# Generated by Django 3.2.2 on 2021-05-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('tenancy', '0012_standardize_models'),
        #('ipam', '0046_set_vlangroup_scope_types'),
        #('dcim', '0131_consoleport_speed'),
        ('netbox_bgp', '0016_netbox_bgp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asn',
            unique_together={('number', 'site', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='bgpsession',
            unique_together={('device', 'local_address', 'local_as', 'remote_address', 'remote_as')},
        ),
        migrations.AlterUniqueTogether(
            name='routingpolicy',
            unique_together={('name', 'description')},
        ),
    ]
