# Generated by Django 3.2 on 2021-05-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0046_set_vlangroup_scope_types'),
        ('dcim', '0131_consoleport_speed'),
        ('netbox_bgp', '0017_netbox_bgp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpsession',
            name='ibgp_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ipam.ipaddress'),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='ibgp_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ibgp_device', to='dcim.device'),
        ),
    ]
