# Generated by Django 3.2 on 2021-05-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_bgp', '0018_netbox_bgp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgpsession',
            name='ibgp_address',
        ),
    ]
