# Generated by Django 3.2 on 2021-05-17 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0046_set_vlangroup_scope_types'),
        ('netbox_bgp', '0019_netbox_bgp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgpsession',
            name='remote_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remote_address', to='ipam.ipaddress'),
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='remote_as',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remote_as', to='netbox_bgp.asn'),
        ),
    ]
