# Generated by Django 3.2.12 on 2022-03-16 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0053_asn_model'),
        ('netbox_bgp', '0020_netbox_bgp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asngroup',
            name='site',
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='local_as',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_as', to='ipam.asn'),
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='remote_as',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remote_as', to='ipam.asn'),
        ),
        migrations.DeleteModel(
            name='ASN',
        ),
        migrations.DeleteModel(
            name='ASNGroup',
        ),
    ]
