# Generated by Django 4.0.6 on 2022-07-29 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0057_created_datetimefield'),
        ('netbox_bgp', '0022_netbox_bgp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asngroup',
            name='site',
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='local_as',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_as', to='ipam.asn'),
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='remote_as',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remote_as', to='ipam.asn'),
        ),
        migrations.DeleteModel(
            name='ASN',
        ),
        migrations.DeleteModel(
            name='ASNGroup',
        ),
    ]
