# Generated by Django 4.0.4 on 2022-08-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_bgp', '0024_netbox_bgp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingpolicyrule',
            name='match_ip_address',
            field=models.ManyToManyField(blank=True, related_name='plrules', to='netbox_bgp.prefixlist'),
        ),
        migrations.AlterField(
            model_name='routingpolicyrule',
            name='match_ipv6_address',
            field=models.ManyToManyField(blank=True, related_name='plrules6', to='netbox_bgp.prefixlist'),
        ),
    ]
