# Generated by Django 4.1.9 on 2023-07-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_bgp', '0028_netbox_bgp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgppeergroup',
            name='export_prefix_lists',
            field=models.ManyToManyField(blank=True, related_name='group_export_prefix_lists', to='netbox_bgp.prefixlist'),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='import_prefix_lists',
            field=models.ManyToManyField(blank=True, related_name='group_import_prefix_lists', to='netbox_bgp.prefixlist'),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='export_prefix_lists',
            field=models.ManyToManyField(blank=True, related_name='session_export_prefix_lists', to='netbox_bgp.prefixlist'),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='import_prefix_lists',
            field=models.ManyToManyField(blank=True, related_name='session_import_prefix_lists', to='netbox_bgp.prefixlist'),
        ),
    ]
