# Generated by Django 5.0.9 on 2024-11-19 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
        ('ipam', '0070_vlangroup_vlan_id_ranges'),
        ('netbox_bgp', '0032_netbox_bgp'),
        ('virtualization', '0040_convert_disk_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bgpsession',
            unique_together={('device', 'local_address', 'local_as', 'remote_address', 'remote_as')},
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='virtualmachine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='virtualization.virtualmachine'),
        ),
        migrations.AlterUniqueTogether(
            name='bgpsession',
            unique_together={('device', 'local_address', 'local_as', 'remote_address', 'remote_as'), ('virtualmachine', 'local_address', 'local_as', 'remote_address', 'remote_as')},
        ),
    ]
