# Generated by Django 5.2.4 on 2025-08-12 08:08

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0208_devicerole_uniqueness'),
        ('extras', '0129_fix_script_paths'),
        ('ipam', '0081_remove_service_device_virtual_machine_add_parent_gfk_index'),
        ('netbox_bgp', '0035_alter_aspathlist_options_and_more'),
        ('tenancy', '0020_remove_contactgroupmembership'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspathlistrule',
            options={'ordering': ['aspath_list', 'index']},
        ),
        migrations.AlterUniqueTogether(
            name='aspathlist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bgppeergroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='communitylist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prefixlist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='routingpolicy',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aspathlist',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ASPathList', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BGPPeerGroup', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='communitylist',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CommunityList', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='prefixlist',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrefixList', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='routingpolicy',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RoutingPolicy', to='dcim.site'),
        ),
        migrations.AlterUniqueTogether(
            name='aspathlist',
            unique_together={('name', 'description', 'site')},
        ),
        migrations.AlterUniqueTogether(
            name='bgppeergroup',
            unique_together={('name', 'description', 'site')},
        ),
        migrations.AlterUniqueTogether(
            name='communitylist',
            unique_together={('name', 'description', 'site')},
        ),
        migrations.AlterUniqueTogether(
            name='prefixlist',
            unique_together={('name', 'description', 'family', 'site')},
        ),
        migrations.AlterUniqueTogether(
            name='routingpolicy',
            unique_together={('name', 'description', 'site')},
        ),
        migrations.CreateModel(
            name='Redistributing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('redistribute_source', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.device')),
                ('redistribute_policy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='redistributing', to='netbox_bgp.routingpolicy')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('virtualmachine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualization.virtualmachine')),
                ('vrf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipam.vrf')),
            ],
            options={
                'verbose_name_plural': 'Redistributing',
                'unique_together': {('name', 'device', 'redistribute_source', 'vrf', 'site')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
