# Generated by Django 5.2.8 on 2025-11-28 12:54

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0215_rackreservation_status'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('ipam', '0083_vlangroup_populate_total_vlan_ids'),
        ('netbox_bgp', '0036_alter_routingpolicy_options_routingpolicy_weight'),
        ('tenancy', '0020_remove_contactgroupmembership'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redistributing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=256)),
                ('scope_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('redistribute_source', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Redistributing',
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='bgpsession',
            options={'ordering': ('name', 'pk')},
        ),
        migrations.AlterUniqueTogether(
            name='aspathlist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bgppeergroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='communitylist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prefixlist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='routingpolicy',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aspathlist',
            name='scope_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aspathlist',
            name='scope_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='scope_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='scope_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='communitylist',
            name='scope_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitylist',
            name='scope_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='prefixlist',
            name='scope_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefixlist',
            name='scope_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='routingpolicy',
            name='scope_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routingpolicy',
            name='scope_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='aspathlist',
            index=models.Index(fields=['scope_type', 'scope_id'], name='netbox_bgp__scope_t_903943_idx'),
        ),
        migrations.AddIndex(
            model_name='bgppeergroup',
            index=models.Index(fields=['scope_type', 'scope_id'], name='netbox_bgp__scope_t_376c40_idx'),
        ),
        migrations.AddIndex(
            model_name='communitylist',
            index=models.Index(fields=['scope_type', 'scope_id'], name='netbox_bgp__scope_t_cec8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='prefixlist',
            index=models.Index(fields=['scope_type', 'scope_id'], name='netbox_bgp__scope_t_a37fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='routingpolicy',
            index=models.Index(fields=['scope_type', 'scope_id'], name='netbox_bgp__scope_t_484ff4_idx'),
        ),
        migrations.AddConstraint(
            model_name='aspathlist',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_id', 'name', 'description'), name='netbox_bgp_aspathlist_unique_scope_name_description'),
        ),
        migrations.AddConstraint(
            model_name='bgppeergroup',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_id', 'name', 'description'), name='netbox_bgp_bgppeergroup_unique_scope_name_description'),
        ),
        migrations.AddConstraint(
            model_name='communitylist',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_id', 'name', 'description'), name='netbox_bgp_communitylist_unique_scope_name_description'),
        ),
        migrations.AddConstraint(
            model_name='prefixlist',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_id', 'name', 'description', 'family'), name='netbox_bgp_prefixlist_unique_scope_name_description'),
        ),
        migrations.AddConstraint(
            model_name='routingpolicy',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_id', 'name', 'description'), name='netbox_bgp_routingpolicy_unique_scope_name_description'),
        ),
        migrations.AddField(
            model_name='redistributing',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.device'),
        ),
        migrations.AddField(
            model_name='redistributing',
            name='redistribute_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redistributing', to='netbox_bgp.routingpolicy'),
        ),
        migrations.AddField(
            model_name='redistributing',
            name='scope_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='redistributing',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='redistributing',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='redistributing',
            name='virtualmachine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtualization.virtualmachine'),
        ),
        migrations.AddField(
            model_name='redistributing',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipam.vrf'),
        ),
        migrations.AddIndex(
            model_name='redistributing',
            index=models.Index(fields=['scope_type', 'scope_id'], name='netbox_bgp__scope_t_a7effb_idx'),
        ),
        migrations.AddConstraint(
            model_name='redistributing',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_id', 'name', 'device', 'virtualmachine', 'redistribute_source', 'vrf'), name='netbox_bgp_redistributing_unique_scope_name_description'),
        ),
    ]
