# Generated by Django 5.2.9 on 2026-04-23 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0085_add_comments_to_organizationalmodel'),
        ('netbox_bgp', '0039_bgpsession_remote_as_macro'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgppeergroup',
            name='local_as',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_local_as', to='ipam.asn'),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='prefix_list_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_prefix_in', to='netbox_bgp.prefixlist'),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='prefix_list_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_prefix_out', to='netbox_bgp.prefixlist'),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='remote_as',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_remote_as', to='ipam.asn'),
        ),
    ]
