# Generated by Django 5.2.9 on 2026-04-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_bgp', '0040_netbox_bgp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgppeergroup',
            name='extra_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='extra_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
