# Generated by Django 6.0.7 on 2026-08-14 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0250_cooling_infrastructure'),
        ('extras', '0143_event_rule_action_registry'),
        ('ipam', '0097_merge_ipaddress_host_index_and_multi_protocol_services'),
        ('netbox_bgp', '0041_netbox_bgp'),
        ('tenancy', '0026_consolidate_unique_constraints'),
        ('virtualization', '0060_consolidate_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpsession',
            name='remote_prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remote_prefix', to='ipam.prefix'),
        ),
        migrations.AlterField(
            model_name='bgpsession',
            name='remote_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remote_address', to='ipam.ipaddress'),
        ),
        migrations.AddConstraint(
            model_name='bgpsession',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False), ('remote_prefix__isnull', False)), fields=('device', 'local_address', 'local_as', 'remote_prefix', 'remote_as'), name='netbox_bgp_bgpsession_unique_device_remote_prefix'),
        ),
        migrations.AddConstraint(
            model_name='bgpsession',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_prefix__isnull', False), ('virtualmachine__isnull', False)), fields=('virtualmachine', 'local_address', 'local_as', 'remote_prefix', 'remote_as'), name='netbox_bgp_bgpsession_unique_vm_remote_prefix'),
        ),
    ]
