# Generated by Django 6.1 on 2026-09-16 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_bgp', '0042_netbox_bgp'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitylistrule',
            name='community_custom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='communitylistrule',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='netbox_bgp.community'),
        ),
    ]
