# Generated by Django 6.1.1 on 2026-10-09 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_bgp', '0043_netbox_bgp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='value',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('(?:(?:[\\d\\.\\*]|\\\\d|\\[\\^?[\\d\\-\\.]+\\])(?:[+?]|\\{\\d+(?:,\\d*)?\\})?)+:(?:(?:[\\d\\.\\*]|\\\\d|\\[\\^?[\\d\\-\\.]+\\])(?:[+?]|\\{\\d+(?:,\\d*)?\\})?)+')]),
        ),
    ]
