# Generated by Django 6.1 on 2026-09-18 11:17

from django.db import migrations, models


def migrate_site_to_scope(apps, schema_editor):
    """Carry existing Community.site values over to the generic scope field."""
    Community = apps.get_model("netbox_bgp", "Community")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Site = apps.get_model("dcim", "Site")
    site_ct = ContentType.objects.get_for_model(Site)
    Community.objects.filter(site__isnull=False, scope_type__isnull=True).update(
        scope_type=site_ct,
        scope_id=models.F("site_id"),
    )


def migrate_scope_to_site(apps, schema_editor):
    """Reverse migrate_site_to_scope: write Site scopes back to the legacy site FK."""
    Community = apps.get_model("netbox_bgp", "Community")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Site = apps.get_model("dcim", "Site")
    site_ct = ContentType.objects.get_for_model(Site)
    Community.objects.filter(scope_type=site_ct, scope_id__isnull=False).update(
        site_id=models.F("scope_id"),
    )


class Migration(migrations.Migration):

    # NetBox FKs are DEFERRABLE INITIALLY DEFERRED: the data migration's UPDATE on
    # scope_type/scope_id leaves pending deferred-FK events that would block the
    # DROP COLUMN in the same transaction ("pending trigger events"). Run each
    # operation in its own transaction so the backfill commits before the DDL.
    atomic = False

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0144_customfield_status"),
        ("ipam", "0097_merge_ipaddress_host_index_and_multi_protocol_services"),
        ("netbox_bgp", "0044_community_scope_id_community_scope_type"),
        ("tenancy", "0026_consolidate_unique_constraints"),
    ]

    operations = [
        migrations.RunPython(migrate_site_to_scope, migrate_scope_to_site),
        migrations.RemoveField(
            model_name="community",
            name="site",
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(
                fields=["scope_type", "scope_id"], name="netbox_bgp__scope_t_50d47c_idx"
            ),
        ),
    ]
